# Generated by Django 4.1.3 on 2024-06-27 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.researcher')),
            ],
        ),
        migrations.AddField(
            model_name='researcher',
            name='projects',
            field=models.ManyToManyField(blank=True, to='app.researchproject'),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('publication_date', models.DateField()),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.researchproject')),
            ],
        ),
    ]
