# Generated by Django 4.1.3 on 2024-06-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='projects',
            field=models.ManyToManyField(blank=True, to='app.researchproject'),
        ),
    ]
